### ISSUE TITLE
有计划公开数据库吗?

### ISSUE THREAD

**Issue by HunYuanfeng** [terryqj0107/RiSAWOZ#1]
您好，我打算用您的数据集研究对话策略学习和data-to-text generation，请问有计划公开数据库吗?

**Comment by terryqj0107** [comment]
您好，现在可以下载了，之前backend database似乎有点问题，已重新上传，希望对您有帮助。

**Comment by RaleLee** [comment]
Hi! Thank you for releasing this dataset! I found that the backend database for each dialogue is very small in [source data](https://github.com/terryqj0107/RiSAWOZ/blob/master/RiSAWOZ-data/source-data.zip). And I can't find the whole database in your repo like [CrossWOZ database](https://github.com/thu-coai/CrossWOZ/tree/master/data/crosswoz/database).
Is there any plan to make the **whole** database public? Thanks for your help! : )

**Comment by terryqj0107** [comment]
@RaleLee Hi! I'm very glad that you're interested in our dataset. For your need, I have uploaded the database and ontology now. You can down load the database file if you are in need. I hope it's helpful for you.

**Comment by RaleLee** [comment]
Thanks for help! I hope to make a good work on your dataset!
