### ISSUE TITLE
请问在任务Context-to-Text Generation中的inform和success的评测脚本可以开源么

### ISSUE THREAD

**Issue by Mervyn-1** [terryqj0107/RiSAWOZ#4]

**Comment by terryqj0107** [comment]
You can get the source codes and models of the five benchmark tasks from Google Drive (URL: https://drive.google.com/drive/folders/1LFEY2h0WGikOG1-fMAAnF0NkR8zpyoTG?usp=sharing) or BaiduNetDisk (URL: https://pan.baidu.com/s/1BQImRCvnnP_nQzXVM1CTZQ), the password for BaiduNetDisk is 73jl.
